version: '0.0.1'
source: "https://github.com/tr7zw/ForgeFabricComposeTemplate/tree/1.18.2/"
replacements:
  group: "dev.tr7zw"
  name: "AnimatedFirstPerson"
  id: "animatedfirstperson"
  version: "1.0.0"
  author: "tr7zw"
  dependencies: ""
  licensename: "LICENSE"
rootProject:
  template: "."
subProjects:
  AFP-Fabric:
    template: "Fabric"
  AFP-Forge:
    template: "Forge"